// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4EmailTemplateDemo
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\twesh\source\repos\T4EmailTemplateDemo\T4EmailTemplateDemo\BodyTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class BodyTemplate : EmailComponentTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<p>Hi there ");
            
            #line 6 "C:\Users\twesh\source\repos\T4EmailTemplateDemo\T4EmailTemplateDemo\BodyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(FirstName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 6 "C:\Users\twesh\source\repos\T4EmailTemplateDemo\T4EmailTemplateDemo\BodyTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(LastName));
            
            #line default
            #line hidden
            this.Write("</p>\r\n<p>This is an Example of a Body.</p>\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 8 "C:\Users\twesh\source\repos\T4EmailTemplateDemo\T4EmailTemplateDemo\BodyTemplate.tt"

	public string FirstName { get; set; }
	public string LastName { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
